# Śniadania

## Owsiana zapiekanka z bananem i płatkami czekoladowymi

### Lista składników
- 4 banany
- 240 g płatków owsianych
- 480 ml mleka
- 30 g (2 łyżki) milkyway stars 
- 42 g (2 łyżki) miodu 
- 2 jajka
- 14 g (1 łyżka) masła
- 40 g mąki 
- 20 g cukru
- łyżeczka proszku do pieczenia

(mąke i cukier można zastąpić 60 g dowolnego białka w proszku)

### Przygotowanie

1. Nagrzej piekarnik do 190 C.
2. W dużej misce wymieszaj płatki owsiane, mąke, cukier i proszek do pieczenia.
3. W innej misce zmiażdż 3 banany. Następnie wymieszaj z jajkami, roztopionym masłem, mlekiem oraz miodem. 
4. Wsyp zawartość jednej miski do drugiej i wymieszaj. Dodaj połowe milkyway stars.
4. Natłuść naczynie żaroodporne i wlej do niego zawartość miski, umieść na wierzchu prokojonego w plastry ostaniego banana i pozostałe milkyway stars.
5. Umieść naczynie w piekarniku i piecz przez 35-45 minut.

[Przepis pochodzi z blogu Meal Prep Manual](https://mealprepmanual.com/chocolate-chip-banana-bread-baked-oatmeal/)

## Owsiana zapiekanka z jabłkami

### Lista składników

### Przygotowanie