# Obiady

## Dal z czarnej soczewicy


### Lista składników

- 350 gram czarnej soczewiczy
- 1,25 l wody
- 1 łyżeczka chili
- 1,5 łyżeczki mielonego kuminu
- 3 lub 4 ząbki czosnku
- 3 cm imbiru
- 1 cebula
- 1 puszka pomidorów
- 3 łyżki koncentratu
- 1/4 łyżki brązowego cukru

- 1/2 puszki mleka kokosowego
-  1/2 łyżeczki zmielonych ziaren kolendry
- 1/4 łyżeczki czarnego pieprzu
- 1/4 łyżeczki cynamonu
- 1/4 łyżeczki gałki muszkatałowej


### Przygotowanie
1. Soczewicę opłukać, dodać do dużego garnka razem z wodą i solą. Gotować pod przykryciem do momentu, aż zmięknie, czyli około 25 – 30 minut.
2. Przygotować pozostałe dodatki. Czosnek obrać i posiekać, imbir zetrzeć na tarce, cebulę pokroić w kostkę.
3. Na dnie patelni rozgrzać olej, wrzucić chili oraz kumin i smażyć przez kilkanaście sekund. Wtedy wrzucić czosnek, imbir oraz cebulę i smażyć 5 – 6 minut do momentu, aż cebula zrobi się lekko złota i miękka.
4. Do takiej cebuli dodać pomidory, koncentrat pomidory oraz szczyptę cukru i gotować przez 10 – 15 minut na niedużym ogniu.
5. Do miękkiej soczewicy dodać pomidorowy sos z patelni oraz wszystkie pozostałe przyprawy. Zamieszać kilka razy i gotować ostatnie 2 – 3 minuty.
6. Podawać z kolendrą lub pietruszką oraz opcjonalnie z odrobiną kokosowego mleka. Dobre bez żadnych dodatków, a dla osób wyjątkowo głodnych można podać z ulubionym ryżem. Następnie dnia bardzo gęstnieje i smakuje jeszcze lepiej.




[Przepis pochodzi z blogu jadłonomia](https://www.jadlonomia.com/przepisy/dal-z-czarnej-soczewicy/)

## Pomidorowe curry z ciecierzycy

### Lista składników

- 1 cebula
- 1 łyżeczka gorczycy, można zastąpić musztardą
- 1/2 łyżeczki soli
- olej
- 1 łyżeczka kuminu, zmielonego
- 1/2 łyżeczki kurkumy
- szczypta płatków chili
- szczypta cynamonu
- 1 puszka mleka kokosowego 
- 1 puszka pomidorów krojonych
- 1 łyżka sosu sojowego
- 1/2 łyżeczki cukru trzcinowego
- półtorej szklanki suchej ciecierzycy


### Przygotowanie
1. Ciecierzyce namoczyć przez noc i gotować przez 1.5 godziny.
2. Cebulę pokroić w kostkę, na dnie dużej patelni rozgrzać olej. Dodać cebulę, gorczycę i sól, smażyć na średnim ogniu przez 4 – 5 minut.
3. Do podsmażonej cebuli dodać kumin, kurkumę, chili oraz cynamon. Zamieszać, smażyć przez kilkanaście sekund i dodać kokosowe mleko, pomidory, sos sojowy oraz cukier. Zwiększyć ogień na maksymalny i gotować przez 5 – 8 minut, czyli do momentu, aż sos się lekko zagęści i zrobi się błyszczący.
4. Dodać odsączoną ciecierzycę, zmniejszyć ogień na średni i gotować przez 5 – 6 minut. Doprawić do smaku solą lub w razie potrzeby większą ilością cukru trzcinowego. Podawać z ryżem i ulubionymi warzywami, które można zanurzać w kremowym sosie.


[Przepis pochodzi z blogu jadłonomia](https://www.jadlonomia.com/przepisy/pomidorowe-curry-z-ciecierzycy/)



## Kokosowy Dal

### Lista składników


- 3 szklanki czerwonej soczewicy / 600 g
- 2 cebule
- 1 puszka pomidorów
- 1 puszka mleczka kokosowego
- 3 łyżeczki mielonego kuminu
- 2 łyżeczki ziaren musztardowca
- 2 łyżeczki mielonych ziaren kolendry
- 1 łyżeczka kurkumy
- ½ łyżeczki chili
- 5 ½ szklanki wody
- olej do smażenia



### Przygotowanie

1. Na dnie dużego garnka rozgrzać olej, cebulę pokroić w kostkę i dodać na olej razem ze wszystkimi przyprawami i pomidorami. Wszystko dokładnie wymieszać, dodać soczewicę i ponownie wymieszać. Wlać wodę i gotować na niedużym ogniu przez około 15 – 25 minut, czyli do czasu, aż soczewica wchłonie większość wody.
2. Spróbować soczewicy i doprawić do smaku solą. Dodać mleko kokosowe, zamieszać i gotować jeszcze 5 – 10 minut, jeśli w międzyczasie soczewica zacznie wypijać za dużo płynu dolać więcej wody. Podawać z ryżem, komosą lub plackami naan, najlepiej smakuje drugiego i trzeciego dnia.

[Przepis pochodzi z blogu jadłonomia](https://www.jadlonomia.com/przepisy/kokosowy-dal-z-czerwonej-soczewicy/)

## Zimowa caponata z selera

### Lista składników

- 500 g selera / 1 duża bulwa
- 5 łyżek oliwy
- 3 ząbki czosnku
- szczypta płatków chili
- 2 łyżki kaparów
- 4 łyżki czarnych oliwek
- 2 puszki krojonych pomidorów
- 3 łyżki octu balsamicznego
- 2 łyżki migdałów
- 1 łyżka rodzynek

Do podania: naprawdę świetnie smakuje z rukolą

### Przygotowanie


1. Selera obrać i pokroić w grubą kostkę. Na dnie dużego garnka wlać tyle oliwy, żeby przykryła dno, rozgrzać ją i dodać selera. Smażyć na średnim ogniu mieszając bardzo rzadko lub wcale. Smażyć przez 8 – 10 minut czyli do momentu, aż seler będzie złocisty i miękki w środku.
2. W tym czasie przygotować wszystkie pozostałe składniki, dodatkowo czosnek posiekać, a migdały podprażyć i posiekać.
3. Kiedy seler będzie miękki wyjąć go z garnka, odłożyć na papierowy ręcznik i porządnie oprószyć solą oraz pieprzem. Na oliwę w garnku włożyć czosnek oraz płatki chili, smażyć przez kilkanaście sekund, czyli do momentu, aż czosnek się zezłoci. Wtedy oliwki oraz kapary, smażyć kolejne kilkanaście sekund.
4. Dodać pomidory, ocet balsamiczny, migdały, rodzynki oraz sól i czarny pieprz. Garnek przykryć i gotować przez 25 minut na małym ogniu.
5. Do gotowego pomidorowego sosu dodać usmażonego selera, wymieszać, doprawić do smaku i podawać skropione oliwą. Dobrze smakuje zarówno na ciepło jak i na zimno, świetnie smakuje z rukolą.

[Przepis pochodzi z blogu jadłonomia](https://www.jadlonomia.com/przepisy/zimowa-caponata-z-selera/)

## Japoński gryczany makaron na zimno


### Lista składników

- 150 gram makaronu soba
- pół pęczka szczypiorku
- 1 łyżeczka oleju sezamowego
- 1 łyżeczka octu ryżowego
- 2 łyżeczki sambal olek
- łyżeczka cukru/syrop cukrowy
- 3 łyżki sosu sojowego
- 2 łyżki sezamu


### Przygotowanie
1. Makaron ugotować i ostudzić zimną wodą.
2. Z reszty składników zrobić sos.
3. Wymieszać sos z makaronem.

## Unohana

### Lista składników

- 150 gram Okary
- pół średniej cebuli
- 20g suszonych grzybów (najlepiej shiitake)
- pół małej marchewki
- 3 łyżki cukru
- 3 łyżki sosu sojowego
- 1 łyżka mirin
- 200 ml wody
- 1/4 szczypiorku
- łyżka oleju

### Przygotowanie

1. Namoczyć suszone grzyby shiitake z 200 ml wody w lodówce przez 8-10 godzin.
2. Wyciśnij płyn z każdego grzyba.
3. Drobno pokrój grzyby, cebulę, marchew i szczypiorek (możesz dodać inne warzywa).
4. Połącz cukier, sos sojowy i mirin z wodą, w której grzyby moczyły się przez noc i odstaw na bok. 
5. Na patelni rozgrzać oliwę i podsmażyć cebulę, aż stanie się półprzezroczysta.
6. Dodaj pozostałe pokrojone warzywa (oprócz szczypiorku) i smaż razem z cebulą.
7. Dodaj okarę i gotuj, aż stanie się krucha.
8. Na patelnię wlej mieszankę przypraw i wodę z moczenia grzybów. 
9. Mieszaj wszystko razem na małym ogniu, aż płyn odparuje.
10. Dodać szalotki i lekko podsmażyć, a następnie wyłączyć ogień.

[Przepis pochodzi z blogu chopstick chronicles](https://www.chopstickchronicles.com/unohana-sauteed-okara-vegetables/)
