# Ogólne

## Tofu

### Lista składników

Składniki na około 360 g tofu. Konieczna również będzie chusta serowarska oraz prasa do tofu.

- 500 gm nasion soi
- dużo wody
- 2 łyżeczki nigari


### Przygotowanie

1. Wypłucz nasiona soi.
2. Zalej dużą ilością wody i namocz przez 8-12 godzin.
3. Odlej wode i zblenduj nasiona z dwiema porcjami świeżej wody (dwa razy tyle ile soi).
4. Za pomocą chusty serowarskiej oodziel mleko sojowe od pulpy z nasion (Okary). Do zrobienia tofu będzie potrzebne tylko mleko.
5. Doprowadź do wrzenia mleka a następnei zredukuj gaz i mieszaj przez 7-10 minut.
6. Wyłącz gaz i pozwól mleku ochłonąć przez 5 minut.
7. Wymieszaj nigari z 125 ml ciepłej wody.
8. Dodaj uzyskany roztwór do mleka i lekko zamieszaj. Przez najbliższe 10 minut będzie formował się twaróg.
9. Zmontuj prasę i wyłóż ją chustą.
10. Gdy twaróg będzie gotowy odcedź go i umieść w prasie, zawiń dokładnie chustą.
11. Zakryj prasę przykrywką i umieść na niej coś ciężkiego (1,5 kg jest wystarczające). Za 30 minut tofu będzie gotowe.


