# Pasty kanapkowe


## Smalec z białej fasoli z dodatkiem jabłka


### Lista składników 

Na jeden słoik:

- 2 cebule
- 1 jabłko
- 2 liście laurowe
- 1 ziele angielskie
- 1 goździk
- 1 jałowiec
- olej

- 1 puszka białej fasoli lub 1 ½ szklanki ugotowanej fasoli
- ½ łyżeczki majeranku
- ¼ łyżeczki lubczyku
- 1 łyżeczka sosu sojowego
- sól i pieprz

### Przygotowanie

1. Cebulę posiekać w kostkę, jabłko obrać i pokroić w kostkę. Na patelni rozgrzać olej i dodać posiekaną cebulkę oraz jabłko wraz z zielem, jałowcem, goździkiem i liśćmi laurowymi. Smażyć na małym ogniu do czasu, aż cebulka będzie złota a jabłka miękkie.
2. W międzyczasie fasolę odcedzić, opłukać i zmiksować przy pomocy blendera razem z sosem sojowym, majerankiem, sporą szczyptą pieprzu, soli i ¼ szklanki zimnej wody, odstawić.
3. Z podsmażonej cebulki i jabłka wyłowić przyprawy, z którymi wszystko się smażyło. Dodać to wszystko do zmiksowanej fasoli, miksując krótko na niezbyt wysokich obrotach. Ważne jest, żeby wszystkie składniki się połączyły, ale żeby blender nie zmielił ich na gładką pastę – kawałki cebulki i jabłek powinny być wyczuwalne. Doprawić do smaku solą i pieprzem, można dodać też kilka kropli sosu sojowego więcej. Najlepiej smakuje następnego dnia po schłodzeniu w lodówce.

[Przepis pochodzi z blogu jadłonomia](https://www.jadlonomia.com/przepisy/wegetarianski-smalec-z-jabkie/)